
ssh_logger:
  timezone_location: "America/Chicago"
  process_loop_sleep_seconds: 5
  ssh_user: "mpenning"
  ssh_host: "localhost"
  ssh_authentication: "password"
  ssh_prompt_regex: \$
  ssh_privilege_command:
  prefix_command: "date"
  commands:
  - "ls -la | grep vim"
  - "exit"

