
ssh_logger:
  timezone_location: "America/Chicago"
  ## Set ssh_loop_sleep_seconds to 0 for unit tests
  ssh_loop_sleep_seconds: 0
  ssh_user: "rviews"
  ssh_host: "route-views.routeviews.org"
  ssh_authentication: "none"
  ssh_prompt_regex: "route-views(>|#)"
  ssh_privilege_command: "! no enable command"
  prefix_command: "show clock"
  commands:
  - "terminal length 0"
  - "show ip route 1.1.1.1"
  - "show ip bgp 1.1.1.1 best"
  - "exit"

