
ssh_logger:
  timezone_location: America/Chicago
  process_loop_sleep_seconds: 5
  ssh_user: rviews
  ssh_host: route-views.routeviews.org
  ssh_authentication: none
  ssh_prompt_regex: route-views(>|#)
  ssh_enable_command: enable
  prefix_command: show clock
  commands:
  - terminal length 0
  - show ip route 1.1.1.1
  - show ip bgp 1.1.1.1 best
  - exit

